docker-build-main:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed samsonemeje/udagram-api-feed:latest
    - docker push docker.io/samsonemeje/udagram-api-feed

    - docker build -t udagram-api-user ./udagram-api-user
    - docker tag udagram-api-user samsonemeje/udagram-api-user:latest
    - docker push docker.io/samsonemeje/udagram-api-user

    - docker build -t udagram-frontend ./udagram-frontend
    - docker tag udagram-frontend samsonemeje/udagram-frontend:latest
    - docker push docker.io/samsonemeje/udagram-frontend

    - docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - docker tag udagram-reverseproxy samsonemeje/reverseproxy:latest
    - docker push docker.io/samsonemeje/reverseproxy

  only:
    - main

docker-build-image:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed samsonemeje/udagram-api-feed:latest
    - docker push docker.io/samsonemeje/udagram-api-feed

    - docker build -t udagram-api-user ./udagram-api-user
    - docker tag udagram-api-user samsonemeje/udagram-api-user:latest
    - docker push docker.io/samsonemeje/udagram-api-user

    - docker build -t udagram-frontend ./udagram-frontend
    - docker tag udagram-frontend samsonemeje/udagram-frontend:latest
    - docker push docker.io/samsonemeje/udagram-frontend

    - docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - docker tag udagram-reverseproxy samsonemeje/reverseproxy:latest
    - docker push docker.io/samsonemeje/reverseproxy

  except:
    - main
